name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '20 5 * * 1'
  push:
    branches: [main]

permissions:
  # Keep workflow-level permissions read-only to satisfy Scorecard workflow verification.
  read-all: true

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed for publishing signed results.
      id-token: write
      # Needed only for SARIF upload step.
      security-events: write
    steps:
      - name: Run analysis
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@f5c2471be782132e47a6e6f9c725e56730d6e9a3
        with:
          sarif_file: results.sarif
